default_language_version:
  python: python3.11
fail_fast: false
repos:
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.2
    hooks:
      - id: codespell

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-comprehensions==3.17.0
          - flake8-walrus==1.2.0

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-builtin-literals
      - id: check-ast
      - id: check-json
      - id: detect-private-key
      - id: requirements-txt-fixer
      - id: trailing-whitespace
        args: [ --markdown-linebreak-ext=md ]
      - id: mixed-line-ending
        args: [ --fix=crlf ]

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v4.0.0
    hooks:
      - id: add-trailing-comma

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 26.5.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 8.0.1
    hooks:
      - id: isort
