name: Lint

on:
  push:
    branches:
      - v1

  pull_request:


jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0

      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1  # v6.3.0
        with:
          python-version-file: ".python-version"

      - name: Lint with black
        uses: psf/black@87928e6d6761a4a6d22250e1fee5601b3998086e  # 26.5.1
        with:
          options: '--check --diff --verbose'
          src: '.'
          use_pyproject: true
